In [6]:
import pandas as pd

In [21]:
df = pd.read_csv(r'C:\Users\felip\PMIFTIR\extractedData\FTIR_Biopolymer blended films of poly butylene succinate  cyclic olefin copolymer.csv')

In [22]:
df

           x     PBS     COC 10PBS/90COC 20PBS/70COC 30PBS/70COC 40PBS/60COC
0     497,95  21,164  35,363      48,864      65,946      77,885      93,637
1     502,05  20,378  35,557      49,118      65,545      77,589      92,708
2     503,88  19,617  35,644      49,232      65,355      77,462      92,255
3     515,27  17,899  36,175      49,929       64,76      76,865      91,029
4     520,49  18,053  36,399      50,235      64,823      76,763      91,105
..       ...     ...     ...         ...         ...         ...         ...
406  3731,56  21,102  36,216       51,27      66,916      79,184      93,937
407  3733,61  21,099  36,223       51,28      66,895      79,141      93,898
408  3733,98  21,098  36,224      51,282      66,891      79,132      93,891
409  3737,23  21,093  36,234      51,299      66,857      79,039      93,829
410   3745,9  21,084  36,262      51,344      66,779      78,673      93,677

[411 rows x 7 columns]